In [1]:
import numpy as np

my_array = np.array([10, 20, 30])

# Write your code here
raw_data = my_array.data

print(type(raw_data))

<class 'memoryview'>


In [2]:
import numpy as np

my_array = np.array([10, 20, 30, 40])

# Write your code here
element_size = my_array.itemsize

print(element_size)

8


In [3]:
import numpy as np
# Create NumPy arrays with different data types
arr_int = np.array([1, 2, 3, 4, 5], dtype=int)
arr_float = np.array([1.0, 2.5, 3.7, 4.2, 5.9], dtype=float)
arr_str = np.array(['apple', 'banana', 'cherry'], dtype=str)
# Print item sizes of each array
print("Item size of arr_int:", arr_int.itemsize, "bytes")
print("Item size of arr_float:", arr_float.itemsize, "bytes")
print("Item size of arr_str:", arr_str.itemsize, "bytes")

Item size of arr_int: 8 bytes
Item size of arr_float: 8 bytes
Item size of arr_str: 24 bytes


In [4]:
import numpy as np

# Given list
my_list = [1.2, 2.3, 3.4] 

# Write your code here
array_int = np.array(my_list, dtype = int)

print(array_int)

[1 2 3]


In [5]:
import numpy as np 
matrix_x = np.array([[10, 20, 30, 40], 
                     [50, 60, 70, 80], 
                     [90, 100, 110, 120]])
matrix_y = matrix_x
print(matrix_y is matrix_x)

True


In [6]:
import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35])
mask = arr % 10 == 0
print(mask)
result = arr[mask]
print(result)

[ True False  True False  True False]
[10 20 30]


In [7]:
import numpy as np
data = np.array([1.0, 2.9, 9+4j])
print(type(data[2]))


<class 'numpy.complex128'>


In [8]:
import numpy as np
arr = np.array([1,2,3])
print(arr.shape)
print(arr.ndim)
print(arr.size)

(3,)
1
3


In [9]:
import numpy as np
arr = np.array([[1],[3]])
print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 1)
2
2


In [10]:
import numpy as np
data = np.array([10, 20, 30, 40, 50])
print(type(data))

<class 'numpy.ndarray'>


In [13]:
import numpy as np

# Given the two NumPy arrays
array1 = np.array([10, 20, 30])
array2 = np.array([2, 5, 10])

c = array1 + array2
print('Addition:',c)

d = array1 - array2
print('Subtraction:',d)

e = array1 * array2
print('Multiplication:',e)

f = array1 / array2
print('Division:',e)

Addition: [12 25 40]
Subtraction: [ 8 15 20]
Multiplication: [ 20 100 300]
Division: [ 20 100 300]


In [17]:
import numpy as np

# Given 2D NumPy array
data = np.array([[25, 180, 75], 
                 [30, 175, 68], 
                 [35, 170, 70], 
                 [40, 165, 80]])

# 1. Extract the first two rows and the first two columns
subarray = data[:2,:2]
print("Extracted 2x2 Subarray:")
print(subarray)

# 2. Extract the last row of the array
last_row = data[-1]
print(f"Last Row: {last_row}")

# 3. Extract all rows but only the second column
second_column = data[:,1]
print(f"Second Column: {second_column}")

Extracted 2x2 Subarray:
[[ 25 180]
 [ 30 175]]
Last Row: [ 40 165  80]
Second Column: [180 175 170 165]


In [21]:
import numpy as np

# Grayscale image
Image = np.array([[0, 255, 128], 
                 [64, 32, 16]])

# Finding dimensions
dimension = Image.ndim

if dimension == 3:
    print("Colored Image")
elif dimension == 2:
    print("Grayscale Image")
else:
    pass

Grayscale Image


In [28]:
import numpy as np

# Given datasets
dataset = np.array([[[1], [3]], 
                     [[5], [7]],
                   [[5], [7]]])

# Calculate rows and columns
row_col = dataset.shape
# Calculate total number of elements present in the dataset
no_of_elements = dataset.size

# Print results
print(f"Rows & Columns in the dataset: {row_col}")
print(f"Number of Elements in the dataset: {no_of_elements}")

Rows & Columns in the dataset: (3, 2, 1)
Number of Elements in the dataset: 6


In [34]:
data = {
    "Temperature": 35,
    "Humidity": 75,
    "Pressure": 1013,
    "WindSpeed": 12
}

# Extracting keys and converting to a NumPy array
keys_array = np.array(list(data.keys()))

print("Array of keys:", keys_array)

Array of keys: ['Temperature' 'Humidity' 'Pressure' 'WindSpeed']


In [36]:
import numpy as np

# Weekly temperature data (C)
temperatures = np.array([
    25, 32, 29, 35, 28, 31, 30, 27, 33, 34, 26, 29, 30, 32, 33, 
    36, 28, 31, 30, 29, 35, 27, 28, 31, 34, 30, 29, 32, 35, 28, 
    33, 26, 29, 30, 34, 32, 36, 28, 31, 30, 29, 33, 28, 30, 31, 
    32, 34, 29, 27, 35, 31, 30, 28, 33, 34, 36, 29, 31, 30, 29, 
    35, 28, 32, 30, 27, 33, 34, 28, 29, 32, 31, 30, 27, 35, 29, 
    30, 32, 34, 31, 28, 33, 30, 29, 32, 36, 28, 35, 30, 29, 31, 
    34, 32, 33, 28, 30, 29
])

# Define the threshold
threshold = 30

# Mask indexing to filter temperatures
filtered_temperatures = temperatures[temperatures > threshold]

print(f"Filtered temperatures greater than {threshold}C:", filtered_temperatures)

Filtered temperatures greater than 30C: [False  True False  True False  True False False  True  True False False
 False  True  True  True False  True False False  True False False  True
  True False False  True  True False  True False False False  True  True
  True False  True False False  True False False  True  True  True False
 False  True  True False False  True  True  True False  True False False
  True False  True False False  True  True False False  True  True False
 False  True False False  True  True  True False  True False False  True
  True False  True False False  True  True  True  True False False False]
